
site_name: NanoTorch is Deep Learning Library from scratch using Numpy and Math. 
site_url: 
site_description: Explore the NanoTorch Library.

repo_url: https://github.com/JamorMoussa/NanoTorch
repo_name: JamorMoussa/NanoTorch

docs_dir: docs

theme:
  name: material
  features:
    - navigation.top
    - navigation.tabs
  palette:
    primary: black

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences


  
plugins:
 - mkdocs-jupyter:
    include_source: True
 - search
 - social

edit_uri: ""

site_author: Moussa JAMOR

nav:
  - Home: 'index.md'


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/moussa-jamor-b17a58253/
    - icon: fontawesome/brands/github
      link: https://github.com/JamorMoussa/
    # - icon: fontawesome/brands/youtube
    #   link: https://www.youtube.com/channel/UCr8O8l5cCX85Oem1d18EezQ

